# Generated by Django 3.0.4 on 2020-05-07 19:27

from django.db import migrations, models
import django.db.models.deletion
import taggit.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnrolledUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identity', models.CharField(editable=False, max_length=100, unique=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('preferred_contact', models.CharField(choices=[('email', 'Email'), ('sms', 'Sms'), ('voice', 'Voice')], default='sms', max_length=15)),
                ('liason', models.BooleanField(default=False)),
                ('twil_messaging_binding_address', models.CharField(blank=True, max_length=100, null=True)),
                ('twil_messaging_proxy_address', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(blank=True, max_length=255, null=True)),
                ('reporting_new_cases', models.BooleanField(default=False)),
                ('last_new_cases_reported', models.IntegerField(default=0)),
                ('last_upload_date', models.DateTimeField(blank=True, null=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('facility_size', models.CharField(blank=True, max_length=20, null=True)),
                ('cluster', models.BooleanField(default=False)),
                ('address', models.TextField(blank=True, null=True)),
                ('liasons', models.CharField(blank=True, max_length=255, null=True)),
                ('emails', models.TextField(blank=True, null=True)),
                ('phones', models.TextField(blank=True, null=True)),
                ('tags', taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
            ],
            options={
                'verbose_name': 'Facility',
                'verbose_name_plural': 'Facilities',
            },
        ),
        migrations.CreateModel(
            name='TwilioConversation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sid', models.CharField(max_length=200)),
                ('account_sid', models.CharField(max_length=200)),
                ('chat_service_sid', models.CharField(max_length=200)),
                ('messaging_service_sid', models.CharField(max_length=200)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='TwilioMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('index', models.PositiveIntegerField()),
                ('author_sid', models.CharField(blank=True, max_length=200, null=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sms.TwilioConversation')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sms.EnrolledUser')),
            ],
        ),
        migrations.CreateModel(
            name='QualtricsSubmission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('facility_name', models.CharField(blank=True, max_length=200, null=True)),
                ('reported_new_cases', models.BooleanField(default=False)),
                ('new_cases', models.IntegerField(default=0)),
                ('facility', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sms.Facility')),
                ('reported_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sms.EnrolledUser')),
            ],
        ),
        migrations.AddField(
            model_name='enrolleduser',
            name='facility',
            field=models.ManyToManyField(blank=True, to='sms.Facility'),
        ),
        migrations.AddField(
            model_name='enrolleduser',
            name='tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
        migrations.CreateModel(
            name='Binding',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_sid', models.CharField(max_length=255)),
                ('binding_sid', models.CharField(max_length=255)),
                ('binding_type', models.CharField(choices=[('sms', 'Sms'), ('facebook-messenger', 'Fb'), ('apn', 'Apn'), ('fcm', 'Fcm'), ('gcm', 'Gcm')], default='sms', max_length=20)),
                ('address', models.CharField(max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sms.EnrolledUser')),
            ],
        ),
    ]
