# Generated by Django 3.0.4 on 2020-06-04 21:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='facility',
            old_name='liasons',
            new_name='liaisons',
        ),
    ]
