# Generated by Django 3.0.7 on 2020-06-22 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0002_auto_20200604_1453'),
    ]

    operations = [
        migrations.AddField(
            model_name='facility',
            name='last_sms_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
